a = input()

print(5 * " " + a * 1)
print(4 * " " + a * 3)
print(3 * " " + a * 5)
print(4 * " " + a * 3)
print(3 * " " + a * 5)
print(2 * " " + a * 7)
print(1 * " " + a * 9)
print(3 * " " + a * 5)
print(2 * " " + a * 7)
print(1 * " " + a * 9)
print(0 * " " + a * 11)
